server:
  port: 8080
  # servlet 上下文路径, 默认 /, 可以通过此方式设置上下文访问路径
  servlet:
    context-path: /im_bird_sys
spring:
  datasource:
    name: im_bird_sys
    # 采用 druid 的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接数据库的url
    url: jdbc:mysql:///im_bird?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 账号和密码
    username: root
    password: root
    # 监控统计
    filters: stat
    # 初始化连接
    initial-size: 2
    # 最大空闲连接数
    max-idle: 10
    # 最小空闲连接数
    min-idle: 1
    # 最大活动连接
    max-active: 20
    # 获取连接超时的等待时间
    max-wait: 60000
    # 间隔多久进行一次检测,检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    # 一个连接池中最小生存的空间
    min-evictable-idle-time-millis: 300000
    # 验证连接有效与否的SQL, 不同的数据配置不同
    validation-query: SELECT 'x'
    # 指明连接是否被空闲连接回收器(如果有) 进行检验,如果检验失败,则连接将被从池中去除
    test-while-idle: true
    # 借出连接时不要测试,否则影响性能
    test-on-borrow: false

# springmvc 视图解析器扫描前缀和后缀为指定名称的路径
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp

# mybatis配置
mybatis:
  # 对象位置
  type-aliases-package: net.luminary.pojo
  # mapper文件位置
  mapper-locations: classpath:mapper/*.xml
  # 指定mybatis全局配置文件中的相关配置项
  configuration:
    # 开启识类中驼峰命名
    map-underscore-to-camel-case: true